;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/12/4 17:16:45

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 1.gif 1.gif
#define IDH_1001	1001	; guo.png guo.png
#define IDH_1002	1002	; hai.png hai.png
#define IDH_1003	1003	; hua.png hua.png
#define IDH_1004	1004	; hui.png hui.png
#define IDH_1005	1005	; lin.png lin.png
#define IDH_1006	1006	; ni.png ni.png
#define IDH_1007	1007	; sguo.png sguo.png
#define IDH_1009	1009	; xi.png xi.png
#define IDH_1010	1010	; xiao.png xiao.png
#define IDH_1011	1011	; zhen.png zhen.png
