;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/12/4 17:16:45

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=1.gif	; 1.gif
IDH_1001=guo.png	; guo.png
IDH_1002=hai.png	; hai.png
IDH_1003=hua.png	; hua.png
IDH_1004=hui.png	; hui.png
IDH_1005=lin.png	; lin.png
IDH_1006=ni.png	; ni.png
IDH_1007=sguo.png	; sguo.png
IDH_1009=xi.png	; xi.png
IDH_1010=xiao.png	; xiao.png
IDH_1011=zhen.png	; zhen.png
